field.field.*.*.*.third_party.entity_reference_validators:
  type: mapping
  label: 'Entity reference validator field settings'
  mapping:
    circular_reference:
      type: boolean
      label: 'Prevent entity from referencing itself'
    duplicate_reference:
      type: boolean
      label: 'Prevent multiple references to the same entity'
