drupal_8_element.people_type.*:
  type: config_entity
  label: 'People type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
