tmgmt.translator.settings.acclaro:
  type: tmgmt.translator_base
  mapping:
    token:
      type: string
      label: Acclaro Web Token
    use_sandbox:
      type: boolean
      label: Use the sandbox
